CREATE SCHEMA `shopping`
DEFAULT CHARACTER SET utf8;
USE `shopping`;
-- 用户角色表
CREATE TABLE `shopping`.`role` (
`ROLE_ID` INT NOT NULL AUTO_INCREMENT,
`ROLE_NAME` VARCHAR (30) NOT NULL UNIQUE,
PRIMARY KEY (`ROLE_ID`)
);

-- 用户表
CREATE TABLE `shopping`.`users` (
`USER_ID` INT NOT NULL AUTO_INCREMENT,
`ROLE_ID` INT NOT NULL,
`USERNAME` VARCHAR (30) NOT NULL,
`REAL_NAME` VARCHAR (30) NULL,
`PASSWORD` VARCHAR (30) NOT NULL,
`PWD_QUESTION` VARCHAR (50) NULL,
`PWD_QUESTION_ANSWER` VARCHAR (50) NULL,
`ADDRESS` VARCHAR (50) NULL,
`PHONE_NO` VARCHAR (50) NULL,
`EMAIL` VARCHAR (50) NULL,
PRIMARY KEY (`USER_ID`),
UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC ),
CONSTRAINT `FK_ROLE`
FOREIGN KEY (`ROLE_ID`)
REFERENCES `shopping`.`ROLE` (`ROLE_ID`)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

-- 商品目录表
CREATE TABLE `shopping`.`category` (
`CATEGORY_ID` INT NOT NULL AUTO_INCREMENT,
`CATEGORY_NAME` VARCHAR (30) NOT NULL,
PRIMARY KEY (`CATEGORY_ID`)
);

-- 商品表
CREATE TABLE `shopping`.`goods` (
`GOODS_ID` INT NOT NULL AUTO_INCREMENT,
`GOODS_NAME` VARCHAR (50) NOT NULL,
`DESCRIPTION` VARCHAR (200) NULL,
`PRICE` DECIMAL (10, 2) NOT NULL,
`CATEGORY_ID` INT NOT NULL,
`IMG_URL` VARCHAR (50) NULL,
PRIMARY KEY (`GOODS_ID`)
);
ALTER TABLE `shopping`.`goods`
ADD CONSTRAINT `FK_GOODS_CATEGORY`
FOREIGN KEY (`CATEGORY_ID`)
REFERENCES `shopping`.`category` (`CATEGORY_ID`)
ON DELETE no action
ON UPDATE no action;

-- 购物车表
CREATE TABLE `shopping`.`shopping_cart` (
`SHOPPING_CART_ID` INT NOT NULL AUTO_INCREMENT,
`USER_ID` INT NULL ,
`TOTAL_AMOUNT` INT NULL,
`SUBTOTAL` DECIMAL (10, 2) NULL,
PRIMARY KEY (`SHOPPING_CART_ID`),
UNIQUE INDEX `user_id_UNIQUE` (`USER_ID` ASC )
);
ALTER TABLE `shopping`.`shopping_cart`
ADD CONSTRAINT `FK_USER`
FOREIGN KEY (`USER_ID`)
REFERENCES `shopping`.`users` (`USER_ID`)
ON DELETE no action
ON UPDATE no action;

-- 购物车详情表
CREATE TABLE `shopping`.`shopping_cart_detail` (
`SHOPPING_CART_DETAIL_ID` INT NOT NULL AUTO_INCREMENT,
`SHOPPING_CART_ID` INT NOT NULL,
`GOODS_ID` INT NOT NULL,
`NUM` INT NOT NULL,
PRIMARY KEY (`SHOPPING_CART_DETAIL_ID`),
CONSTRAINT `FK_SHOPPING_CART`
FOREIGN KEY (`SHOPPING_CART_ID`)
REFERENCES `shopping`.`shopping_cart` (`SHOPPING_CART_ID`),
CONSTRAINT `FK_GOODS`
FOREIGN KEY (`GOODS_ID`)
REFERENCES `shopping`.`goods` (`GOODS_ID`)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

-- 订单表
CREATE TABLE `shopping`.`orders` (
`ORDER_ID` INT NOT NULL AUTO_INCREMENT,
`USERNAME` VARCHAR (30) NOT NULL,
`TOTAL_AMOUNT` INT NOT NULL,
`SUMS` DECIMAL (10, 2) NOT NULL,
`CREATE_TIME` DATE NOT NULL,
PRIMARY KEY (`ORDER_ID`)
);

-- 订单详情表
CREATE TABLE `shopping`.`order_detail` (
`ORDER_DETAIL_ID` INT PRIMARY KEY AUTO_INCREMENT,
`ORDER_ID` INT NOT NULL,
`GOODS_NAME` VARCHAR (50) NOT NULL,
`PRICE` DECIMAL (10, 2) NOT NULL,
`NUM` INT NOT NULL,
`CATEGORY_NAME` VARCHAR(45) NOT NULL ,
`DESCRIPTION` VARCHAR(512) NULL,
`IMG_URL` VARCHAR(512) NULL
);

ALTER TABLE `shopping`.`order_detail`
ADD CONSTRAINT `FK_DETAILS_ORDER`
FOREIGN KEY (`ORDER_ID`)
REFERENCES `shopping`.`orders` (`ORDER_ID`)
ON DELETE no action
ON UPDATE no action;
